simulator:
  symbol: QQQ3 #SXRV #EQQB #SXRV_25022022 #EQQB #SXRV_25022022
  #symbol: nasdaqtr2009_syn_2.0 #LQQ2018
  decimals: 4
  data-directory: data/local
  initial-capital: 50000
  strategy: fleuryv2
  show-trades: true
  show-loss-week: false
  loss-week-threshold: -5.0
  show-max-dd: false
  commission-rate: 0.0000 #0,12 es myinvestor

synthetic:
  base-symbol: NASDAQTR2009
  leverage: 2.0
  data-directory: data/local

optimizer:
  symbol: QQQ3
  data-directory: data/local
  initial-capital: 10000
  commission-rate: 0.0000
  show-progress: true

  tp:
    min: 0.033
    max: 0.033
    step: 0.001

  tph:
    min: 0.001
    max: 0.10
    step: 0.001

  sl:
    min: 0.99
    max: 0.99
    step: 0.001

  open-gap:
    min: 0.005
    max: 0.005
    step: 0.001

  output-file: data/optimization/fleury_optimization.csv
  sort-by: sharpe

tickconverter:
  instrument: EURUSD
  input-directory: /Users/davidrpe/Downloads/eurusd/EURUSD/EURUSD-descomprimido
  output-directory: /Users/davidrpe/repositorios/etfTradingDavidRosa/data/ticks
  timezone: UTC
  frequencies:
    - 1
tickchecker:
  date: 2026-04-17
  time: "08:15"
  input-directory:  /Users/davidrpe/Downloads/eurusd/EURUSD/EURUSD-descomprimido
  one-minute-file: /Users/davidrpe/repositorios/etfTradingDavidRosa/data/ticks/EURUSD_1m.csv
statistical-analysis:
  enabled: true
  input-file: data/ticks/EURUSD_15m.csv
  sma-periods:
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
  close-candles:
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
  hours:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
  direction: SHORT
  output-file: data/statistics/EURUSD_statistics.csv