package com.alphapowertrading.simulator.analysis.sma;

/**
 * Statistics generated by one SMA mean-reverting parameter combination.
 */
public record SMAMeanRevertingResult(
        SMAMeanRevertingParameters parameters,
        int operations,
        double operationsPerYear,
        int winningOperations,
        double winRate,
        double netPips,
        double averagePips,
        double medianPips,

        double averageMaePips,
        double maeP50Pips,
        double maeP75Pips,
        double maeP90Pips,
        double maeP95Pips,
        double maeP99Pips,

        double averageMfePips,
        double mfeP50Pips,
        double mfeP75Pips,
        double mfeP90Pips,
        double mfeP95Pips,
        double mfeP99Pips,

        double profitFactor,
        double sharpeRatio,
        double maxDrawdownPips) {

  public boolean passesMinimumOperations(
          double minimumOperationsPerYear) {

    return operationsPerYear >= minimumOperationsPerYear;
  }
}