simulator:
  symbol: QQQ3
  data-directory: data
  initial-capital: 10000

  #strategy: oppwbyh

  #strategy: oppwGapRecovery
  #strategy: oppwOnlyTp
  strategy: fleury

  show-trades: true

  show-loss-week: true
  loss-week-threshold: -5.0

  show-max-dd: true

  commission-rate: 0.0005