walkforward:
  symbol: QQQ3

  data-directory: data
  output-directory: output/walkforward

  initial-capital: 10000
  commission-rate: 0.0005

  in-sample-months: 24
  out-of-sample-months: 1
  step-months: 1

  show-progress: true

  optimization:
    tp:
      min: 0.03
      max: 0.05
      step: 0.005

    tph:
      min: 0.06
      max: 0.08
      step: 0.005

    sl:
      min: 0.005
      max: 0.02
      step: 0.005